spring.application.name=UserService
logging.level.org.springframework=DEBUG

spring.datasource.driver-className=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/user_service_ecom
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
Spring.jpa.hibernate.ddl-auto=update