spring.application.name=e-com-proj
#logging.level.org.springframework=DEBUG

# PostgresSQL Configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/ecom
spring.datasource.driver-className=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true





